<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-4GS3IR5D" failures="1" tests="3" name="Test" time="0.095" errors="0" timestamp="2021-06-03T00:55:14 IST">
  <testcase classname="tp_test.demo_test" name="add" time="0.015"/>
  <testcase classname="tp_test.demo_test1" name="add" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [4] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [5]
at tp_test.demo_test1.add(demo_test1.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- add -->
  <testcase classname="tp_test.demo_test2" name="add" time="0.0"/>
</testsuite> <!-- Test -->
